config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome'
  get 'home/games'
  get 'home/login'
  get 'home/learn_projectile'
  get 'home/learn_friction'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'games/basketball_game'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# email:string
# password_digest:string
# username:string
#
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format: {
    with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, message: 'Must be a valid email'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in to do that" if Current.user.nil?
  end

end

app/controllers/concerns/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path notice:("Successfully Signed Up!")
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def basketball_game
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
  def games
  end
  def login
  end
  def learn_projectile
  end
  def learn_friction
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!
  def edit
  end

  def update
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path notice:("Successfully Signed Up!")
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end

  def create
    user = User.find_by(username: params[:username])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged In"
    else
      flash[:alert] = "Invalid Email or Password"
      render :new
    end
  end

  def new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/basketball_game.html.erb
<%= stylesheet_link_tag 'games' %>

<div class="body-container">

  <h1>A Basketball game</h1>

  <div class="game-container">
    <canvas id="bb-game-canvas" width="1200px" height="675px"></canvas>
    
  </div>

  Speed:<input id="speed" type="number" placeholder="Enter Speed">
  Angle (degrees):<input id="angle" type="number" placeholder="Enter Angle">
  <button id="setButton">Set</button>

<%= javascript_pack_tag 'bb_canvas.js' %>
</div>

app/views/home/_header.html.erb
<%= stylesheet_link_tag 'header' %>
<header>
  <div class="navbar-container">
    <div class="home">
      <%= link_to root_path, id: 'home' do %>
      Gaming Through Physics<span data-content="Gaming Through Physics" aria-hidden="true"></span>
        <% end %>
    </div>
    <div class="linked-pages">
      <div class="dropdown">
        <button class="learn">Learn &#127891</button>
        <div class="dropdown-content">
          <%= link_to "Projectile Motion", home_learn_projectile_path %>
          <%= link_to "Friction", home_learn_friction_path %>
        </div>
      </div>
        <%= link_to "Games", home_games_path, id: 'games' %>
        <% if Current.user %>
          <%= link_to "Welcome, "+ Current.user.username, home_games_path, id: 'welcome' %>
        <% else %>
          <%= link_to "Login", sign_in_path, id: 'login' %>
        <% end %>
    </div>
  </div>
</header>

app/views/home/games.html.erb
<h1>Made it to the games page</h1>

<%= link_to "Basketball Game", games_basketball_game_path %>

app/views/home/learnFriction.html.erb
<h1>In the learn friction page</h1>

app/views/home/learnProjectile.html.erb
<h1>In the learn projectile page</h1>

app/views/home/learn_friction.html.erb
<div class="body-container">
  <h1 class="main-title">Friction</h1>
  <div class="content-container">
    <p class="friction"><%= image_tag('ice.jpg', id: 'ice') %>
      This paragraph will be an introduction to friction
      and how to understand its laws and stuff. Here is another sentence</p>
  </div>
</div>

app/views/home/learn_projectile.html.erb
<div class="body-container">
  <h1 class="main-title">Projectile Motion</h1>
  <div class="content-container">
      <p class="projectile", id="learn-1"><%= image_tag('shooting-basketball.jpg', id: 'shooting-basketball')  %>
        This paragraph will be an introduction into 2 dimensional projectile motion
      and how to understand its laws and stuff. Here is another sentence</p>
  </div>
</div>

app/views/home/login.html.erb
<div class="body-container">
  <h1>Sign In</h1>
  <div class="sign-in-container">

  </div>
</div>

app/views/home/welcome.html.erb
<div class="body-container">
<h1 id='welcome-message'>Welcome to Gaming Through Physics</h1>


<div id="synopsis-container">
  <span>
   <%= image_tag('physics-paper.jpg', id: 'physics-paper')%>
   <h3 id='brief-synopsis'>Gaming Through Physics makes learning physics fun! </h3>
  </span>
</div>

  <%= button_to "Logout", logout_path, method: :delete %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gaming Through Physics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'home/header' %>
    <%= yield %>
  </body>
</html>